import express from 'express';
import addPost from './../../controllers/posts/addPost.js';
import deletePost from './../../controllers/posts/deletePost.js';
import getAllPosts from './../../controllers/posts/getAllPosts.js';
import getSinglePost from './../../controllers/posts/getSinglePost.js';
import updatePost from './../../controllers/posts/updatePost.js';
import verifyJWT from './../../middlewares/verifyJWT.js';
const router = express.Router();
router.get('/get-all-posts/:teamID', verifyJWT, getAllPosts);
router.get('/:postID', verifyJWT, getSinglePost);
router.post('/', verifyJWT, addPost);
router.patch('/:postID', verifyJWT, updatePost);
router.delete('/:postID', verifyJWT, deletePost);
export default router;