import express from 'express';
import addUser from './../../controllers/users/addUser.js';
import getSingleUser from './../../controllers/users/getSingleUser.js';
import updateUser from './../../controllers/users/updateUser.js';
import verifyJWT from './../../middlewares/verifyJWT.js';
const router = express.Router();
router.post('/', addUser);
router.get('/:userID', verifyJWT, getSingleUser);
router.patch('/:userID', verifyJWT, updateUser);
export default router;  