import express from 'express';
import getSinglePostVote from './../../controllers/postVotes/getSinglePostVote.js';
import addOrUpdatePostVote from './../../controllers/postVotes/addOrUpdatePostVote.js';
import deletePostVote from './../../controllers/postVotes/deletePostVote.js';
import verifyJWT from './../../middlewares/verifyJWT.js';
const router = express.Router();
router.get('/:postVoteID', verifyJWT, getSinglePostVote);
router.post('/', verifyJWT, addOrUpdatePostVote);
router.delete('/:postVoteID', verifyJWT, deletePostVote);
export default router;